//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Application.MainModule.com.admingest {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsFactAdmingestControllerBinding", Namespace="urn:WsFactAdmingestControllerwsdl")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ImpuestoTrasladado))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ImpuestoRetenido))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ImpuestoConceptoRetenido))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ImpuestoConceptoTrasladado))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Concepto))]
    public partial class WsFactAdmingestControllerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback holaMundoOperationCompleted;
        
        private System.Threading.SendOrPostCallback agregarClienteAdmingestOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarAutofacturacionAdmingestOperationCompleted;
        
        private System.Threading.SendOrPostCallback generarFacturaAdmingestOperationCompleted;
        
        private System.Threading.SendOrPostCallback generarFacturaEstructuraAdmingestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsFactAdmingestControllerService() {
            this.Url = global::Application.MainModule.Properties.Settings.Default.Application_MainModule_com_admingest_WsFactAdmingestControllerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event holaMundoCompletedEventHandler holaMundoCompleted;
        
        /// <remarks/>
        public event agregarClienteAdmingestCompletedEventHandler agregarClienteAdmingestCompleted;
        
        /// <remarks/>
        public event registrarAutofacturacionAdmingestCompletedEventHandler registrarAutofacturacionAdmingestCompleted;
        
        /// <remarks/>
        public event generarFacturaAdmingestCompletedEventHandler generarFacturaAdmingestCompleted;
        
        /// <remarks/>
        public event generarFacturaEstructuraAdmingestCompletedEventHandler generarFacturaEstructuraAdmingestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:WsFactAdmingestControllerwsdl#holaMundo", RequestNamespace="urn:WsFactAdmingestControllerwsdl", ResponseNamespace="urn:WsFactAdmingestControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string holaMundo(string nombre) {
            object[] results = this.Invoke("holaMundo", new object[] {
                        nombre});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void holaMundoAsync(string nombre) {
            this.holaMundoAsync(nombre, null);
        }
        
        /// <remarks/>
        public void holaMundoAsync(string nombre, object userState) {
            if ((this.holaMundoOperationCompleted == null)) {
                this.holaMundoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnholaMundoOperationCompleted);
            }
            this.InvokeAsync("holaMundo", new object[] {
                        nombre}, this.holaMundoOperationCompleted, userState);
        }
        
        private void OnholaMundoOperationCompleted(object arg) {
            if ((this.holaMundoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.holaMundoCompleted(this, new holaMundoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:WsFactAdmingestControllerwsdl#agregarClienteAdmingest", RequestNamespace="urn:WsFactAdmingestControllerwsdl", ResponseNamespace="urn:WsFactAdmingestControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public WsRespCliente agregarClienteAdmingest(string Usuario, string Contrasena, string RFC, string DatosCliente) {
            object[] results = this.Invoke("agregarClienteAdmingest", new object[] {
                        Usuario,
                        Contrasena,
                        RFC,
                        DatosCliente});
            return ((WsRespCliente)(results[0]));
        }
        
        /// <remarks/>
        public void agregarClienteAdmingestAsync(string Usuario, string Contrasena, string RFC, string DatosCliente) {
            this.agregarClienteAdmingestAsync(Usuario, Contrasena, RFC, DatosCliente, null);
        }
        
        /// <remarks/>
        public void agregarClienteAdmingestAsync(string Usuario, string Contrasena, string RFC, string DatosCliente, object userState) {
            if ((this.agregarClienteAdmingestOperationCompleted == null)) {
                this.agregarClienteAdmingestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnagregarClienteAdmingestOperationCompleted);
            }
            this.InvokeAsync("agregarClienteAdmingest", new object[] {
                        Usuario,
                        Contrasena,
                        RFC,
                        DatosCliente}, this.agregarClienteAdmingestOperationCompleted, userState);
        }
        
        private void OnagregarClienteAdmingestOperationCompleted(object arg) {
            if ((this.agregarClienteAdmingestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.agregarClienteAdmingestCompleted(this, new agregarClienteAdmingestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:WsFactAdmingestControllerwsdl#registrarAutofacturacionAdmingest", RequestNamespace="urn:WsFactAdmingestControllerwsdl", ResponseNamespace="urn:WsFactAdmingestControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public WsRespAutofacturacion registrarAutofacturacionAdmingest(string Usuario, string Contrasena, string RFC, string conceptos, string ticket, string codigo, string total, string descuento, string metodopago, string cuenta) {
            object[] results = this.Invoke("registrarAutofacturacionAdmingest", new object[] {
                        Usuario,
                        Contrasena,
                        RFC,
                        conceptos,
                        ticket,
                        codigo,
                        total,
                        descuento,
                        metodopago,
                        cuenta});
            return ((WsRespAutofacturacion)(results[0]));
        }
        
        /// <remarks/>
        public void registrarAutofacturacionAdmingestAsync(string Usuario, string Contrasena, string RFC, string conceptos, string ticket, string codigo, string total, string descuento, string metodopago, string cuenta) {
            this.registrarAutofacturacionAdmingestAsync(Usuario, Contrasena, RFC, conceptos, ticket, codigo, total, descuento, metodopago, cuenta, null);
        }
        
        /// <remarks/>
        public void registrarAutofacturacionAdmingestAsync(string Usuario, string Contrasena, string RFC, string conceptos, string ticket, string codigo, string total, string descuento, string metodopago, string cuenta, object userState) {
            if ((this.registrarAutofacturacionAdmingestOperationCompleted == null)) {
                this.registrarAutofacturacionAdmingestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarAutofacturacionAdmingestOperationCompleted);
            }
            this.InvokeAsync("registrarAutofacturacionAdmingest", new object[] {
                        Usuario,
                        Contrasena,
                        RFC,
                        conceptos,
                        ticket,
                        codigo,
                        total,
                        descuento,
                        metodopago,
                        cuenta}, this.registrarAutofacturacionAdmingestOperationCompleted, userState);
        }
        
        private void OnregistrarAutofacturacionAdmingestOperationCompleted(object arg) {
            if ((this.registrarAutofacturacionAdmingestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarAutofacturacionAdmingestCompleted(this, new registrarAutofacturacionAdmingestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:WsFactAdmingestControllerwsdl#generarFacturaAdmingest", RequestNamespace="urn:WsFactAdmingestControllerwsdl", ResponseNamespace="urn:WsFactAdmingestControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public WsRespFacturacion generarFacturaAdmingest(string Usuario, string Contrasena, string RFC, string idautofacturacion, string RFCCliente, string idSucursal, string identificador, string UsoCFDI) {
            object[] results = this.Invoke("generarFacturaAdmingest", new object[] {
                        Usuario,
                        Contrasena,
                        RFC,
                        idautofacturacion,
                        RFCCliente,
                        idSucursal,
                        identificador,
                        UsoCFDI});
            return ((WsRespFacturacion)(results[0]));
        }
        
        /// <remarks/>
        public void generarFacturaAdmingestAsync(string Usuario, string Contrasena, string RFC, string idautofacturacion, string RFCCliente, string idSucursal, string identificador, string UsoCFDI) {
            this.generarFacturaAdmingestAsync(Usuario, Contrasena, RFC, idautofacturacion, RFCCliente, idSucursal, identificador, UsoCFDI, null);
        }
        
        /// <remarks/>
        public void generarFacturaAdmingestAsync(string Usuario, string Contrasena, string RFC, string idautofacturacion, string RFCCliente, string idSucursal, string identificador, string UsoCFDI, object userState) {
            if ((this.generarFacturaAdmingestOperationCompleted == null)) {
                this.generarFacturaAdmingestOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenerarFacturaAdmingestOperationCompleted);
            }
            this.InvokeAsync("generarFacturaAdmingest", new object[] {
                        Usuario,
                        Contrasena,
                        RFC,
                        idautofacturacion,
                        RFCCliente,
                        idSucursal,
                        identificador,
                        UsoCFDI}, this.generarFacturaAdmingestOperationCompleted, userState);
        }
        
        private void OngenerarFacturaAdmingestOperationCompleted(object arg) {
            if ((this.generarFacturaAdmingestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generarFacturaAdmingestCompleted(this, new generarFacturaAdmingestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:WsFactAdmingestControllerwsdl#generarFacturaEstructuraAdmingest", RequestNamespace="urn:WsFactAdmingestControllerwsdl", ResponseNamespace="urn:WsFactAdmingestControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public WsRespFacturacion generarFacturaEstructuraAdmingest(string Usuario, string Contrasena, string RFC, Comprobante Comprobante) {
            object[] results = this.Invoke("generarFacturaEstructuraAdmingest", new object[] {
                        Usuario,
                        Contrasena,
                        RFC,
                        Comprobante});
            return ((WsRespFacturacion)(results[0]));
        }
        
        /// <remarks/>
        public void generarFacturaEstructuraAdmingestAsync(string Usuario, string Contrasena, string RFC, Comprobante Comprobante) {
            this.generarFacturaEstructuraAdmingestAsync(Usuario, Contrasena, RFC, Comprobante, null);
        }
        
        /// <remarks/>
        public void generarFacturaEstructuraAdmingestAsync(string Usuario, string Contrasena, string RFC, Comprobante Comprobante, object userState) {
            if ((this.generarFacturaEstructuraAdmingestOperationCompleted == null)) {
                this.generarFacturaEstructuraAdmingestOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenerarFacturaEstructuraAdmingestOperationCompleted);
            }
            this.InvokeAsync("generarFacturaEstructuraAdmingest", new object[] {
                        Usuario,
                        Contrasena,
                        RFC,
                        Comprobante}, this.generarFacturaEstructuraAdmingestOperationCompleted, userState);
        }
        
        private void OngenerarFacturaEstructuraAdmingestOperationCompleted(object arg) {
            if ((this.generarFacturaEstructuraAdmingestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generarFacturaEstructuraAdmingestCompleted(this, new generarFacturaEstructuraAdmingestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WsFactAdmingestControllerwsdl")]
    public partial class WsRespCliente {
        
        private bool successField;
        
        private string messageField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WsFactAdmingestControllerwsdl")]
    public partial class ImpuestoTrasladado {
        
        private string impuestoField;
        
        private string tipoFactorField;
        
        private float tasaOCuotaField;
        
        private float importeField;
        
        /// <remarks/>
        public string Impuesto {
            get {
                return this.impuestoField;
            }
            set {
                this.impuestoField = value;
            }
        }
        
        /// <remarks/>
        public string TipoFactor {
            get {
                return this.tipoFactorField;
            }
            set {
                this.tipoFactorField = value;
            }
        }
        
        /// <remarks/>
        public float TasaOCuota {
            get {
                return this.tasaOCuotaField;
            }
            set {
                this.tasaOCuotaField = value;
            }
        }
        
        /// <remarks/>
        public float Importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WsFactAdmingestControllerwsdl")]
    public partial class ImpuestoRetenido {
        
        private string impuestoField;
        
        private float importeField;
        
        /// <remarks/>
        public string Impuesto {
            get {
                return this.impuestoField;
            }
            set {
                this.impuestoField = value;
            }
        }
        
        /// <remarks/>
        public float Importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WsFactAdmingestControllerwsdl")]
    public partial class Impuesto {
        
        private float totalImpuestosRetenidosField;
        
        private float totalImpuestosTrasladadosField;
        
        private ImpuestoRetenido[] impuestoRetenidoField;
        
        private ImpuestoTrasladado[] impuestoTrasladadoField;
        
        /// <remarks/>
        public float TotalImpuestosRetenidos {
            get {
                return this.totalImpuestosRetenidosField;
            }
            set {
                this.totalImpuestosRetenidosField = value;
            }
        }
        
        /// <remarks/>
        public float TotalImpuestosTrasladados {
            get {
                return this.totalImpuestosTrasladadosField;
            }
            set {
                this.totalImpuestosTrasladadosField = value;
            }
        }
        
        /// <remarks/>
        public ImpuestoRetenido[] ImpuestoRetenido {
            get {
                return this.impuestoRetenidoField;
            }
            set {
                this.impuestoRetenidoField = value;
            }
        }
        
        /// <remarks/>
        public ImpuestoTrasladado[] ImpuestoTrasladado {
            get {
                return this.impuestoTrasladadoField;
            }
            set {
                this.impuestoTrasladadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WsFactAdmingestControllerwsdl")]
    public partial class ImpuestoConceptoRetenido {
        
        private float baseField;
        
        private string impuestoField;
        
        private string tipoFactorField;
        
        private float tasaOCuotaField;
        
        private float importeField;
        
        /// <remarks/>
        public float Base {
            get {
                return this.baseField;
            }
            set {
                this.baseField = value;
            }
        }
        
        /// <remarks/>
        public string Impuesto {
            get {
                return this.impuestoField;
            }
            set {
                this.impuestoField = value;
            }
        }
        
        /// <remarks/>
        public string TipoFactor {
            get {
                return this.tipoFactorField;
            }
            set {
                this.tipoFactorField = value;
            }
        }
        
        /// <remarks/>
        public float TasaOCuota {
            get {
                return this.tasaOCuotaField;
            }
            set {
                this.tasaOCuotaField = value;
            }
        }
        
        /// <remarks/>
        public float Importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WsFactAdmingestControllerwsdl")]
    public partial class ImpuestoConceptoTrasladado {
        
        private float baseField;
        
        private string impuestoField;
        
        private string tipoFactorField;
        
        private float tasaOCuotaField;
        
        private float importeField;
        
        /// <remarks/>
        public float Base {
            get {
                return this.baseField;
            }
            set {
                this.baseField = value;
            }
        }
        
        /// <remarks/>
        public string Impuesto {
            get {
                return this.impuestoField;
            }
            set {
                this.impuestoField = value;
            }
        }
        
        /// <remarks/>
        public string TipoFactor {
            get {
                return this.tipoFactorField;
            }
            set {
                this.tipoFactorField = value;
            }
        }
        
        /// <remarks/>
        public float TasaOCuota {
            get {
                return this.tasaOCuotaField;
            }
            set {
                this.tasaOCuotaField = value;
            }
        }
        
        /// <remarks/>
        public float Importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WsFactAdmingestControllerwsdl")]
    public partial class Concepto {
        
        private string claveProdServField;
        
        private string noIdentificacionField;
        
        private float cantidadField;
        
        private string claveUnidadField;
        
        private string unidadField;
        
        private string descripcionField;
        
        private float valorUnitarioField;
        
        private float importeField;
        
        private float descuentoField;
        
        private ImpuestoConceptoTrasladado[] impuestoConceptoTrasladadoField;
        
        private ImpuestoConceptoRetenido[] impuestoConceptoRetenidoField;
        
        /// <remarks/>
        public string ClaveProdServ {
            get {
                return this.claveProdServField;
            }
            set {
                this.claveProdServField = value;
            }
        }
        
        /// <remarks/>
        public string NoIdentificacion {
            get {
                return this.noIdentificacionField;
            }
            set {
                this.noIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        public float Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        public string ClaveUnidad {
            get {
                return this.claveUnidadField;
            }
            set {
                this.claveUnidadField = value;
            }
        }
        
        /// <remarks/>
        public string Unidad {
            get {
                return this.unidadField;
            }
            set {
                this.unidadField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public float ValorUnitario {
            get {
                return this.valorUnitarioField;
            }
            set {
                this.valorUnitarioField = value;
            }
        }
        
        /// <remarks/>
        public float Importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
        
        /// <remarks/>
        public float Descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
            }
        }
        
        /// <remarks/>
        public ImpuestoConceptoTrasladado[] ImpuestoConceptoTrasladado {
            get {
                return this.impuestoConceptoTrasladadoField;
            }
            set {
                this.impuestoConceptoTrasladadoField = value;
            }
        }
        
        /// <remarks/>
        public ImpuestoConceptoRetenido[] ImpuestoConceptoRetenido {
            get {
                return this.impuestoConceptoRetenidoField;
            }
            set {
                this.impuestoConceptoRetenidoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WsFactAdmingestControllerwsdl")]
    public partial class Receptor {
        
        private string rfcField;
        
        private string nombreField;
        
        private string usoCFDIField;
        
        private string correoElectronicoField;
        
        /// <remarks/>
        public string Rfc {
            get {
                return this.rfcField;
            }
            set {
                this.rfcField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string UsoCFDI {
            get {
                return this.usoCFDIField;
            }
            set {
                this.usoCFDIField = value;
            }
        }
        
        /// <remarks/>
        public string CorreoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WsFactAdmingestControllerwsdl")]
    public partial class Comprobante {
        
        private string serieField;
        
        private string folioField;
        
        private string fechaField;
        
        private string formaPagoField;
        
        private float subTotalField;
        
        private float descuentoField;
        
        private string monedaField;
        
        private float tipoCambioField;
        
        private float totalField;
        
        private string tipoDeComprobanteField;
        
        private string metodoPagoField;
        
        private string lugarExpedicionField;
        
        private Receptor receptorField;
        
        private Concepto[] conceptoField;
        
        private Impuesto impuestoField;
        
        /// <remarks/>
        public string Serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        public string Folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
            }
        }
        
        /// <remarks/>
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public string FormaPago {
            get {
                return this.formaPagoField;
            }
            set {
                this.formaPagoField = value;
            }
        }
        
        /// <remarks/>
        public float SubTotal {
            get {
                return this.subTotalField;
            }
            set {
                this.subTotalField = value;
            }
        }
        
        /// <remarks/>
        public float Descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
            }
        }
        
        /// <remarks/>
        public string Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        public float TipoCambio {
            get {
                return this.tipoCambioField;
            }
            set {
                this.tipoCambioField = value;
            }
        }
        
        /// <remarks/>
        public float Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public string TipoDeComprobante {
            get {
                return this.tipoDeComprobanteField;
            }
            set {
                this.tipoDeComprobanteField = value;
            }
        }
        
        /// <remarks/>
        public string MetodoPago {
            get {
                return this.metodoPagoField;
            }
            set {
                this.metodoPagoField = value;
            }
        }
        
        /// <remarks/>
        public string LugarExpedicion {
            get {
                return this.lugarExpedicionField;
            }
            set {
                this.lugarExpedicionField = value;
            }
        }
        
        /// <remarks/>
        public Receptor Receptor {
            get {
                return this.receptorField;
            }
            set {
                this.receptorField = value;
            }
        }
        
        /// <remarks/>
        public Concepto[] Concepto {
            get {
                return this.conceptoField;
            }
            set {
                this.conceptoField = value;
            }
        }
        
        /// <remarks/>
        public Impuesto Impuesto {
            get {
                return this.impuestoField;
            }
            set {
                this.impuestoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WsFactAdmingestControllerwsdl")]
    public partial class WsRespFacturacion {
        
        private bool successField;
        
        private string messageField;
        
        private string urlPdfField;
        
        private string urlXmlField;
        
        private string xMLField;
        
        private string uUIDField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string urlPdf {
            get {
                return this.urlPdfField;
            }
            set {
                this.urlPdfField = value;
            }
        }
        
        /// <remarks/>
        public string urlXml {
            get {
                return this.urlXmlField;
            }
            set {
                this.urlXmlField = value;
            }
        }
        
        /// <remarks/>
        public string XML {
            get {
                return this.xMLField;
            }
            set {
                this.xMLField = value;
            }
        }
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WsFactAdmingestControllerwsdl")]
    public partial class WsRespAutofacturacion {
        
        private bool successField;
        
        private string messageField;
        
        private string idAutofacturacionField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string idAutofacturacion {
            get {
                return this.idAutofacturacionField;
            }
            set {
                this.idAutofacturacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void holaMundoCompletedEventHandler(object sender, holaMundoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class holaMundoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal holaMundoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void agregarClienteAdmingestCompletedEventHandler(object sender, agregarClienteAdmingestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class agregarClienteAdmingestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal agregarClienteAdmingestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WsRespCliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WsRespCliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void registrarAutofacturacionAdmingestCompletedEventHandler(object sender, registrarAutofacturacionAdmingestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarAutofacturacionAdmingestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarAutofacturacionAdmingestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WsRespAutofacturacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WsRespAutofacturacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void generarFacturaAdmingestCompletedEventHandler(object sender, generarFacturaAdmingestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generarFacturaAdmingestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generarFacturaAdmingestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WsRespFacturacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WsRespFacturacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void generarFacturaEstructuraAdmingestCompletedEventHandler(object sender, generarFacturaEstructuraAdmingestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generarFacturaEstructuraAdmingestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generarFacturaEstructuraAdmingestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WsRespFacturacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WsRespFacturacion)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591