--USE [master]
--GO

--/****** Object:  Database [Sagas.MainModule]    Script Date: 23/07/2018 17:54:37 ******/
--CREATE DATABASE [Sagas.MainModule]
-- CONTAINMENT = NONE
-- ON  PRIMARY 
--( NAME = N'Sagas.MainModule', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Sagas.MainModule.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
-- LOG ON 
--( NAME = N'Sagas.MainModule_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Sagas.MainModule_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
--GO

--ALTER DATABASE [Sagas.MainModule] SET COMPATIBILITY_LEVEL = 110
--GO

--IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
--begin
--EXEC [Sagas.MainModule].[dbo].[sp_fulltext_database] @action = 'enable'
--end
--GO

--ALTER DATABASE [Sagas.MainModule] SET ANSI_NULL_DEFAULT OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET ANSI_NULLS OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET ANSI_PADDING OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET ANSI_WARNINGS OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET ARITHABORT OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET AUTO_CLOSE OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET AUTO_CREATE_STATISTICS ON 
--GO

--ALTER DATABASE [Sagas.MainModule] SET AUTO_SHRINK OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET AUTO_UPDATE_STATISTICS ON 
--GO

--ALTER DATABASE [Sagas.MainModule] SET CURSOR_CLOSE_ON_COMMIT OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET CURSOR_DEFAULT  GLOBAL 
--GO

--ALTER DATABASE [Sagas.MainModule] SET CONCAT_NULL_YIELDS_NULL OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET NUMERIC_ROUNDABORT OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET QUOTED_IDENTIFIER OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET RECURSIVE_TRIGGERS OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET  DISABLE_BROKER 
--GO

--ALTER DATABASE [Sagas.MainModule] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET DATE_CORRELATION_OPTIMIZATION OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET TRUSTWORTHY OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET ALLOW_SNAPSHOT_ISOLATION OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET PARAMETERIZATION SIMPLE 
--GO

--ALTER DATABASE [Sagas.MainModule] SET READ_COMMITTED_SNAPSHOT OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET HONOR_BROKER_PRIORITY OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET RECOVERY FULL 
--GO

--ALTER DATABASE [Sagas.MainModule] SET  MULTI_USER 
--GO

--ALTER DATABASE [Sagas.MainModule] SET PAGE_VERIFY CHECKSUM  
--GO

--ALTER DATABASE [Sagas.MainModule] SET DB_CHAINING OFF 
--GO

--ALTER DATABASE [Sagas.MainModule] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
--GO

--ALTER DATABASE [Sagas.MainModule] SET TARGET_RECOVERY_TIME = 0 SECONDS 
--GO

--ALTER DATABASE [Sagas.MainModule] SET  READ_WRITE 
--GO


