//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagas.MainModule.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abono
    {
        public int IdAbono { get; set; }
        public int IdCargo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaAbono { get; set; }
        public decimal MontoAbono { get; set; }
        public byte IdFormaPago { get; set; }
        public string FolioBancario { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual FormaPago CFormaPago { get; set; }
    }
}
