//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagas.MainModule.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmacenGasMovimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlmacenGasMovimiento()
        {
            this.Fotografias = new HashSet<AlmacenGasMovimientoFoto>();
        }
    
        public short IdEmpresa { get; set; }
        public short Year { get; set; }
        public byte Mes { get; set; }
        public byte Dia { get; set; }
        public short Orden { get; set; }
        public byte IdTipoMovimiento { get; set; }
        public Nullable<byte> IdTipoEvento { get; set; }
        public Nullable<short> IdOrdenVenta { get; set; }
        public short IdAlmacenGas { get; set; }
        public short IdCAlmacenGasPrincipal { get; set; }
        public Nullable<short> IdCAlmacenGasReferencia { get; set; }
        public Nullable<int> IdAlmacenEntradaGasDescarga { get; set; }
        public Nullable<int> IdAlmacenGasRecarga { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string CAlmacenPrincipalNombre { get; set; }
        public string CAlmacenReferenciaNombre { get; set; }
        public string OperadorChoferNombre { get; set; }
        public string TipoEvento { get; set; }
        public string TipoMovimiento { get; set; }
        public Nullable<decimal> RemanenteKg { get; set; }
        public Nullable<decimal> RemanenteLt { get; set; }
        public decimal EntradaKg { get; set; }
        public decimal EntradaLt { get; set; }
        public decimal SalidaKg { get; set; }
        public decimal SalidaLt { get; set; }
        public decimal CantidadActualKg { get; set; }
        public decimal CantidadActualLt { get; set; }
        public Nullable<decimal> CantidadAcumuladaDiaKg { get; set; }
        public Nullable<decimal> CantidadAcumuladaDiaLt { get; set; }
        public Nullable<decimal> CantidadAcumuladaMesKg { get; set; }
        public Nullable<decimal> CantidadAcumuladaMesLt { get; set; }
        public Nullable<decimal> CantidadAcumuladaAnioKg { get; set; }
        public Nullable<decimal> CantidadAcumuladaAnioLt { get; set; }
        public System.DateTime FechaAplicacion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public decimal CantidadAnteriorGeneralKg { get; set; }
        public decimal CantidadAnteriorGeneralLt { get; set; }
        public decimal CantidadActualGeneralKg { get; set; }
        public decimal CantidadActualGeneralLt { get; set; }
        public decimal PorcentajeAnteriorGeneral { get; set; }
        public decimal PorcentajeActualGeneral { get; set; }
        public decimal CantidadAnteriorKg { get; set; }
        public decimal CantidadAnteriorLt { get; set; }
        public decimal CantidadActualTotalKg { get; set; }
        public decimal CantidadActualTotalLt { get; set; }
        public decimal PorcentajeAnterior { get; set; }
        public decimal PorcentajeActual { get; set; }
    
        public virtual AlmacenGasDescarga Descarga { get; set; }
        public virtual AlmacenGas Inventario { get; set; }
        public virtual AlmacenGasRecarga Recarga { get; set; }
        public virtual UnidadAlmacenGas UnidadAlamcen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmacenGasMovimientoFoto> Fotografias { get; set; }
    }
}
