//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagas.MainModule.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Almacen()
        {
            this.Entradas = new HashSet<AlmacenEntradaProducto>();
            this.Salidas = new HashSet<AlmacenSalidaProducto>();
        }
    
        public int IdAlmacen { get; set; }
        public short IdEmpresa { get; set; }
        public int IdProduto { get; set; }
        public decimal Cantidad { get; set; }
        public string Ubicacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public System.DateTime FechaRegistro { get; set; }    

        public virtual Producto Producto { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmacenEntradaProducto> Entradas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmacenSalidaProducto> Salidas { get; set; }
    }
}
