//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagas.MainModule.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmacenGasMovimientoFoto
    {
        public short IdEmpresa { get; set; }
        public short Year { get; set; }
        public byte Mes { get; set; }
        public byte Dia { get; set; }
        public short Orden { get; set; }
        public short OrdenImagen { get; set; }
        public Nullable<short> IdTipoMedidor { get; set; }
        public string UrlImagen { get; set; }
        public string PathImagen { get; set; }
        public string NombreMedidorLectura { get; set; }
        public decimal Lectura { get; set; }
        public string Evento { get; set; }
    
        public virtual AlmacenGasMovimiento Movimiento { get; set; }
    }
}
