//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagas.MainModule.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmacenGas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlmacenGas()
        {
            this.EntradasGas = new HashSet<AlmacenGasDescarga>();
            this.CAlmacenGas = new HashSet<UnidadAlmacenGas>();
        }
    
        public short IdAlmacenGas { get; set; }
        public short IdEmpresa { get; set; }
        public decimal CapacidadTotalLt { get; set; }
        public decimal CapacidadTotalKg { get; set; }
        public decimal CantidadActualLt { get; set; }
        public decimal CantidadActualKg { get; set; }
        public decimal PorcentajeActual { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmacenGasDescarga> EntradasGas { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnidadAlmacenGas> CAlmacenGas { get; set; }
    }
}
