//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagas.MainModule.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionUtilitarios
    {
        public int IdAsignacionUtilitario { get; set; }
        public short IdEmpresa { get; set; }
        public int IdUtilitario { get; set; }
        public int IdChoferOperador { get; set; }
        public System.DateTime FechaMdidificacion { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual OperadorChofer COperadorChofer { get; set; }
        public virtual CUtilitario CUtilitario { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
