//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagas.MainModule.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDetalleEquipoTransporte
    {
        public int Id_DetalleEtransporte { get; set; }
        public int Id_Vehiculo { get; set; }
        public Nullable<bool> EsCamioneta { get; set; }
        public Nullable<bool> EsPipa { get; set; }
        public Nullable<bool> EsUtilitario { get; set; }
        public string NumIdVehicular { get; set; }
        public string Placas { get; set; }
        public string NumMotor { get; set; }
        public string DescVehiculo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Color { get; set; }
        public short cilindros { get; set; }
        public int IdTipoCombustible { get; set; }
    
        public virtual Camioneta CCamioneta { get; set; }
        public virtual CCombustible CCombustible { get; set; }
        public virtual CDetalleEquipoTransporte CDetalleEquipoTransporte1 { get; set; }
        public virtual CDetalleEquipoTransporte CDetalleEquipoTransporte2 { get; set; }
        public virtual Pipa CPipa { get; set; }
        public virtual CUtilitario CUtilitario { get; set; }
    }
}
