//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagas.MainModule.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTipoEgreso
    {
        public short IdTipoEgreso { get; set; }
        public string Descripcion { get; set; }
        public bool EsFiscal { get; set; }
        public bool GastoFijo { get; set; }
        public decimal Monto { get; set; }
        public Nullable<int> Periocidad { get; set; }
        public bool Activo { get; set; }
    }
}
