//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagas.MainModule.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaContableAutorizado
    {
        public int IdCuentaContable { get; set; }
        public decimal Autorizado { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdCuentaContableAutorizado { get; set; }
    
        public virtual CuentaContable CCuentaContable { get; set; }
    }
}
