//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagas.MainModule.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleMantenimiento
    {
        public int Id_DetalleMtto { get; set; }
        public DateTime FechaMtto { get; set; }
        public int id_vehiculo { get; set; }
        public bool EsCamioneta { get; set; }
        public bool EsPipa { get; set; }
        public bool EsUtilitario { get; set; }
        public int Id_tipomtto { get; set; }
        public string DescripcionMtto { get; set; }
        public int Kilometraje_Actual { get; set; }
        public string NumeroOC { get; set; }
    
        public virtual Camioneta CCamioneta { get; set; }
        public virtual CMantenimiento CMantenimiento { get; set; }
        public virtual Pipa CPipa { get; set; }
    }
}
