//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagas.MainModule.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso
    {
        public int IdIngreso { get; set; }
        public short IdEmpresa { get; set; }
        public Nullable<int> IdOrdenCompra { get; set; }
        public int IdCuentaContable { get; set; }
        public int IdCentroCosto { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Ticket { get; set; }
        public decimal Monto { get; set; }
        public bool EsRema { get; set; }
        public string Descripcion { get; set; }
    
        public virtual CentroCosto CCentroCosto { get; set; }
        public virtual CuentaContable CCuentaContable { get; set; }
        public virtual OrdenCompra OrdenCompra { get; set; }
    }
}
