//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagas.MainModule.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.PedidoDetalle = new HashSet<PedidoDetalle>();
            this.RespuestaSatisfaccionPedido = new HashSet<RespuestaSatisfaccionPedido>();
        }
    
        public int IdPedido { get; set; }
        public int IdCliente { get; set; }
        public short IdEmpresa { get; set; }
        public short IdEstatusPedido { get; set; }
        public string FolioVenta { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaPedido { get; set; }
        public Nullable<int> IdPipa { get; set; }
        public Nullable<int> IdCamioneta { get; set; }
        public Nullable<int> Ruta { get; set; }
        public short IdDireccion { get; set; }
        public string MotivoCancelacion { get; set; }
        public Nullable<System.DateTime> FechaSurtido { get; set; }
    
        public virtual PedidoEstatus PedidoEstatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoDetalle> PedidoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespuestaSatisfaccionPedido> RespuestaSatisfaccionPedido { get; set; }
    }
}
