//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class PrecioVenta
{
    public short IdPrecioVenta { get; set; }
    public short IdEmpresa { get; set; }
    public byte IdPrecioVentaEstatus { get; set; }
    public short IdCategoria { get; set; }
    public short IdProductoLinea { get; set; }
    public int IdProducto { get; set; }
    public string Categoria { get; set; }
    public string Linea { get; set; }
    public string Producto { get; set; }
    public Nullable<decimal> PrecioActual { get; set; }
    public Nullable<decimal> PrecioPemexKg { get; set; }
    public Nullable<decimal> PrecioPemexLt { get; set; }
    public Nullable<decimal> UtilidadEsperadaKg { get; set; }
    public Nullable<decimal> UtilidadEsperadaLt { get; set; }
    public Nullable<decimal> PrecioSalida { get; set; }
    public Nullable<decimal> PrecioSalidaKg { get; set; }
    public Nullable<decimal> PrecioSalidaLt { get; set; }
    public bool EsGas { get; set; }
    public System.DateTime FechaProgramada { get; set; }
    public System.DateTime FechaRegistro { get; set; }
    public Nullable<System.DateTime> FechaVencimiento { get; set; }
    public bool Activo { get; set; }

    public virtual PrecioVentaEstatus Estatus { get; set; }
    public virtual Producto CProducto { get; set; }
    public virtual CategoriaProducto CCategoria { get; set; }
    public virtual LineaProducto CLinea { get; set; }
    public virtual Empresa Empresa { get; set; }
}
