//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagas.MainModule.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteDelDia
    {
        public short IdEmpresa { get; set; }
        public short Year { get; set; }
        public byte Mes { get; set; }
        public byte Dia { get; set; }
        public short Orden { get; set; }
        public Nullable<int> IdPuntoVenta { get; set; }
        public Nullable<short> IdCAlmacenGas { get; set; }
        public Nullable<int> IdOperadorChofer { get; set; }
        public Nullable<int> IdUsuarioJEC { get; set; }
        public string FolioOperacionDia { get; set; }
        public Nullable<decimal> LitrosVenta { get; set; }
        public Nullable<decimal> KilosVenta { get; set; }
        public Nullable<decimal> PrecioLt { get; set; }
        public Nullable<decimal> PrecioKg { get; set; }
        public Nullable<decimal> ImporteContado { get; set; }
        public Nullable<decimal> ImporteCredito { get; set; }
        public Nullable<decimal> ImporteAnticipos { get; set; }
        public Nullable<decimal> ImporteCortes { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string PuntoVenta { get; set; }
        public string OperadorChofer { get; set; }
        public string UsuarioJEC { get; set; }
        public System.DateTime FechaReporte { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual UnidadAlmacenGas CAlmacenGas { get; set; }
        public virtual OperadorChofer COperadorChofer { get; set; }
        public virtual PuntoVenta CPuntoVenta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
