//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class TipoEvento
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TipoEvento()
    {
        this.AlmacenGasAutoConsumo = new HashSet<AlmacenGasAutoConsumo>();
        this.AlmacenGasCalibracion = new HashSet<AlmacenGasCalibracion>();
        this.AlmacenGasRecarga = new HashSet<AlmacenGasRecarga>();
        this.AlmacenGasTraspaso = new HashSet<AlmacenGasTraspaso>();
    }

    public byte IdTipoEvento { get; set; }
    public string Evento { get; set; }
    public bool Activo { get; set; }
    public System.DateTime FechaRegistro { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AlmacenGasAutoConsumo> AlmacenGasAutoConsumo { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AlmacenGasCalibracion> AlmacenGasCalibracion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AlmacenGasRecarga> AlmacenGasRecarga { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AlmacenGasTraspaso> AlmacenGasTraspaso { get; set; }
}
