//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagas.MainModule.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsoCFDI
    {
        public int Id_UsoCFDI { get; set; }
        public string UsoCFDISAT { get; set; }
        public string Descripcion { get; set; }
        public bool PersonaFisica { get; set; }
        public bool PersonaMoral { get; set; }
        public Nullable<System.DateTime> FechaIniVigencia { get; set; }
        public Nullable<System.DateTime> FechaFinVigencia { get; set; }
    }
}
