//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagas.MainModule.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaCorteAnticipoEC
    {
        public short IdEmpresa { get; set; }
        public short Year { get; set; }
        public byte Mes { get; set; }
        public byte Dia { get; set; }
        public short Orden { get; set; }
        public byte IdTipoOperacion { get; set; }
        public int IdPuntoVenta { get; set; }
        public short IdCAlmacenGas { get; set; }
        public int IdOperadorChofer { get; set; }
        public int IdUsuarioRecibe { get; set; }
        public string FolioOperacionDia { get; set; }
        public string FolioOperacion { get; set; }
        public decimal TotalVenta { get; set; }
        public decimal TotalAnticipado { get; set; }
        public decimal MontoRecortadoAnticipado { get; set; }
        public string TipoOperacion { get; set; }
        public string PuntoVenta { get; set; }
        public string OperadorChofer { get; set; }
        public string UsuarioRecibe { get; set; }
        public bool DatosProcesados { get; set; }
        public System.DateTime FechaCorteAnticipo { get; set; }
        public System.DateTime FechaAplicacion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string NombreRecibe { get; set; }
    
        public virtual UnidadAlmacenGas CAlmacenGas { get; set; }
        public virtual OperadorChofer COperadorChofer { get; set; }
        public virtual PuntoVenta CPuntoVenta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
