//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagas.MainModule.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaCajaGeneral
    {
        public short IdEmpresa { get; set; }
        public short Year { get; set; }
        public byte Mes { get; set; }
        public byte Dia { get; set; }
        public short Orden { get; set; }
        public int IdPuntoVenta { get; set; }
        public short IdCAlmacenGas { get; set; }
        public Nullable<int> IdOperadorChofer { get; set; }
        public Nullable<int> IdUsuarioEntrega { get; set; }
        public int IdUsuarioRecibe { get; set; }
        public string FolioOperacionDia { get; set; }
        public decimal VentaTotal { get; set; }
        public decimal VentaTotalCredito { get; set; }
        public decimal VentaTotalContado { get; set; }
        public decimal OtrasVentas { get; set; }
        public decimal DescuentoTotal { get; set; }
        public decimal DescuentoCredito { get; set; }
        public decimal DescuentoContado { get; set; }
        public decimal DescuentoOtrasVentas { get; set; }
        public bool TodoCorrecto { get; set; }
        public string PuntoVenta { get; set; }
        public string OperadorChofer { get; set; }
        public string UsuarioEntrega { get; set; }
        public string UsuarioRecibe { get; set; }
        public decimal VentaTotalBonificacion { get; set; }
    
        public virtual UnidadAlmacenGas CAlmacenGas { get; set; }
        public virtual OperadorChofer COperadorChofer { get; set; }
        public virtual PuntoVenta CPuntoVenta { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
